### ISSUE TITLE
Running ff outside a git controlled folder gives unexpected results

### ISSUE THREAD

**Issue by pharrisee** [sensorario/ff#1]
If ff is run in a folder that is not a git controlled folder 'ff <command>' produces no results.

Would it not be better to display a message indicating that ff only works within a git controlled folder?  Possibly displaying help about ff as well?

**Comment by sensorario** [comment]
Thank you @pharrisee. I've just fixed this issue. Now running `ff` from a folder without a git repository it is possible to see the following message.

<img width="319" alt="Schermata 2019-04-03 alle 20 52 08" src="https://user-images.githubusercontent.com/820248/55504992-6139dd80-5652-11e9-8900-ca42cf5fcb0f.png">
